### PR TITLE
Relax Faraday version

### PR DESCRIPTION
**Pull request by andreibondarev**
@dreamingtulpa For your review.

I'm working on integrating your gem into [Langchain.rb](https://github.com/andreibondarev/langchainrb) but it won't install unless we relax the `faraday` gem version per this PR. Thank you!

### CODE REVIEW

**Comment by andreibondarev** [comment]
@dreamingtulpa For your review :)

**Comment by dreamingtulpa** [comment]
Hey Andrei. Thank you for the PR. I'm not sure if the gem is compatible with v1 of Faraday. Any reason you still relying on the old version?

**Comment by andreibondarev** [comment]
@dreamingtulpa The test suite passed when I ran it.

But there's a bunch of other gems that had the same problem.

**Comment by dreamingtulpa** [comment]
I took another look at it and it seems latest 1.x versions are indeed compatible. Added another test case to check `faraday-multipart` and it stays green. Your "relaxation" disables the use of 2.x though 😅 I now updated the dependency to `>= 1.0` and bumped the gem. Should work now.

**Comment by andreibondarev** [comment]
@dreamingtulpa Thank you! I'll try it out!

**Comment by andreibondarev** [comment]
@dreamingtulpa Worked like a charm, thank you! https://github.com/andreibondarev/langchainrb/pull/44

**Pull request closed without merging**
